### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by vikramrajkumar** [BitShares/BitShares-JS#75]
https://github.com/BitShares/bitshares/issues/1468

I'm not sure if this is the right repo, move it if it is not. But this belongs to the hosted wallet since it won't happen in any of the local wallets.

**Comment by jcalfee** [comment]
We can't 2FA protect it because you already have the wallet in the client.  The aim here is to be protected from the server and the client.  So, we should instead look at something like multi-sig.  An far more practical approach that will probably handle the more common cases is a withdraw limit.  Both would be nice features but the withdraw limit is a blockchain level feature.  So, that leaves multi-sig in the mean time.  Let me know if there is anything easier we can do in the mean time.

**Comment by kenCode-de** [comment]
The local bts client software that is installed on my linux box cannot have 2FA, I realize that, BUT, all web wallets need 2FA. I can't even imagine logging in to blockchain.info or crptsy without 2FA. A lot of us paranoid types will never use an online finance-related site without 2FA and the ability to use really strong passwords, sometimes 256 chars long.

**Comment by xeroc** [comment]
@kenCode-de 
those services store the (encrypted) private keys for you and only deliver them if you can provde 2FA authentication .. that means on the one hand you have extra security due to 2FA .. but on the other hand means you are on you own if the services goes down.

The webwallet of BTS is built such that the private keys NEVER leaver your machine .. they are stored in the browsers local-storage. Hence, 2FA will not help you .. 

Howeverr, I'd love to see the web_wallet (not just wallet.bitshares.org) to be able to signed from a offline key ..

That would GREATLY benefit security .. and.. as all private keys are HD-ally derived, from a path, deriving the required key from a master-seed/key .. shouldn't be much of an act ..

**Comment by kenCode-de** [comment]
Well, having the option would be nice. I'm with ya either way :)
